# Locate pcap
# This module defines
# PCAP_LIBRARIES
# PCAP_FOUND
# PCAP_INCLUDE_DIR
#

FIND_PATH(PCAP_INCLUDE_DIR pcap.h /usr/include C:/msys64/usr/include C:/msys32/usr/include)

IF(MINGW)
	FIND_LIBRARY(PCAP_LIBRARIES NAMES wpcap PATH C:/msys64/usr/lib C:/msys32/usr/lib) 
ELSE (MINGW)
	FIND_LIBRARY(PCAP_LIBRARIES NAMES pcap PATH /usr/lib) 
ENDIF(MINGW)

IF (PCAP_INCLUDE_DIR AND PCAP_LIBRARIES)
	SET(PCAP_FOUND TRUE)
ENDIF (PCAP_INCLUDE_DIR AND PCAP_LIBRARIES)


IF (PCAP_FOUND)
	IF (NOT Pcap_FIND_QUIETLY)
		MESSAGE(STATUS "Found pcap: ${PCAP_LIBRARIES}")
	ENDIF (NOT Pcap_FIND_QUIETLY)
ELSE (PCAP_FOUND)
	IF (Pcap_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find pcap")
	ENDIF (Pcap_FIND_REQUIRED)
ENDIF (PCAP_FOUND)

