# Locate apr-util
# This module defines
# APRUTIL_LIBRARIES
# APRUTIL_FOUND
# APRUTIL_INCLUDE_DIR
#

FIND_PATH(APRUTIL_INCLUDE_DIR apu.h /usr/include/apr-1 /usr/include/apr-1.0 C:/msys64/usr/include/apr-1 C:/msys32/usr/include/apr-1)

FIND_LIBRARY(APRUTIL_LIBRARIES NAMES aprutil-1 PATH /usr/lib C:/msys64/usr/lib C:/msys32/usr/lib) 

IF (APRUTIL_INCLUDE_DIR AND APRUTIL_LIBRARIES)
	SET(APRUTIL_FOUND TRUE)
ENDIF (APRUTIL_INCLUDE_DIR AND APRUTIL_LIBRARIES)


IF (APRUTIL_FOUND)
	IF (NOT AprUtil_FIND_QUIETLY)
		MESSAGE(STATUS "Found aprutil: ${APRUTIL_LIBRARIES}")
	ENDIF (NOT AprUtil_FIND_QUIETLY)
ELSE (APRUTIL_FOUND)
	IF (AprUtil_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find aprutil")
	ENDIF (AprUtil_FIND_REQUIRED)
ENDIF (APRUTIL_FOUND)

