# Locate netlink
# This module defines
# NETLINK_LIBRARIES
# NETLINK_GENL_LIBRARIES
# NETLINK_FOUND
# NETLINK_INCLUDE_DIR
#

FIND_PATH(NETLINK_INCLUDE_DIR netlink /usr/include/libnl3 C:/msys64/usr/include/libnl3 C:/msys32/usr/include/libnl3)

FIND_LIBRARY(NETLINK_LIBRARIES NAMES nl-3 PATH /usr/lib C:/msys64/usr/lib C:/msys32/usr/lib) 
FIND_LIBRARY(NETLINK_GENL_LIBRARIES NAMES nl-genl-3 PATH C:/msys64/usr/lib C:/msys32/usr/lib) 

IF (NETLINK_INCLUDE_DIR AND NETLINK_LIBRARIES AND NETLINK_GENL_LIBRARIES)
	SET(NETLINK_FOUND TRUE)
ENDIF (NETLINK_INCLUDE_DIR AND NETLINK_LIBRARIES AND NETLINK_GENL_LIBRARIES)


IF (NETLINK_FOUND)
	IF (NOT Netlink_FIND_QUIETLY)
		MESSAGE(STATUS "Found netlink: ${NETLINK_LIBRARIES} ${NETLINK_GENL_LIBRARIES}")
	ENDIF (NOT Netlink_FIND_QUIETLY)
ELSE (NETLINK_FOUND)
	IF (Netlink_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find netlink")
	ENDIF (Netlink_FIND_REQUIRED)
ENDIF (NETLINK_FOUND)

