# Locate iwlib
# This module defines
# IWLIB_FOUND
# IWLIB_INCLUDE_DIR
# IWLIB_LIBRARIES
#

FIND_PATH(IWLIB_INCLUDE_DIR iwlib.h /usr/include C:/msys64/usr/include C:/msys32/usr/include)

FIND_LIBRARY(IWLIB_LIBRARIES NAMES iw PATH /usr/lib C:/msys64/usr/lib C:/msys32/usr/lib) 

IF (IWLIB_INCLUDE_DIR AND IWLIB_LIBRARIES)
	SET(IWLIB_FOUND TRUE)
ENDIF (IWLIB_INCLUDE_DIR AND IWLIB_LIBRARIES)


IF (IWLIB_FOUND)
	IF (NOT Iwlib_FIND_QUIETLY)
		MESSAGE(STATUS "Found iwlib: ${IWLIB_LIBRARIES}")
	ENDIF (NOT Iwlib_FIND_QUIETLY)
ELSE (IWLIB_FOUND)
	IF (Iwlib_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find iwlib")
	ENDIF (Iwlib_FIND_REQUIRED)
ENDIF (IWLIB_FOUND)

