// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef wtftp_gui_h
#define wtftp_gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
Fl_Double_Window* make_window();
#endif
